-- Migration 002: Sync SQLite with Supabase Schema
-- This migration is now empty because all tables and columns were already included in the initial schema (001)
-- Keeping this file to maintain migration sequence 